global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'app'
    metrics_path: '/actuator/prometheus'
    static_configs:
    # Provide your ip and Do not give localhost as we are running the Prometheus in docker
    - targets: ['app:8080']
      labels:
        application: app
